# # # try # # #
# num = 0
#
# try:
#     result = 23456 / num
#     if num == 2:
#         raise Exception('message')
#
# except ValueError as value_err:
#     print(value_err)
#
# except ZeroDivisionError as zero_err:
#     print(zero_err)
#
# except Exception as err:
#     print(err)
#
# else:
#     print('Спрацьовує якщо блок try виконався успішно')
#
# finally:
#     print('Спрацьовує в будь-якому разі')


#